* Designing a waveform generator according to a set of specifications 

** SPECIFICATIONS:

*** Waveform Functions:

    -Triangular or Square wave output (User Selectable)

*** Frequency Range:

    -Range #1 ≈ 100 Hz to 1800 Hz 
    -Range #2 ≈ 20 Hz to 360 Hz    

Both ranges user selectable

*** Input Voltage Control Range:

    -0.1V to 5V   

*** Output Amplitude Control Range:

-0V to 8V pk-pk  

Building and Designing was a steady process from the basics to the final product, which can be seen in this repository. 

This project was a steady process to design a waveform generator. I first
started with the basics/fundementals of the design. One hurdle is the
actually generating two types of frequencies in the that same Op-Amp
circuit.  

For the triangle wave, an _Inverting Integrator_ can be used:  

* Inverting Integrator

*pic*   

\[i = \frac{vi(s) - 0}{z_i} =  \frac{vo(s) - 0}{z_f}\] 

\[i = \frac{vi(s)}{z_i} =  \frac{vo(s)}{z_f}\]  

\[i = \frac{vi(s)}{vo(s)} = -\frac{z_i}{z_f}\] or     

\[i = \frac{vo(s)}{vi(s)} = -\frac{z_f}{z_i}\]

In an inverting integrator z_f is a capacitor, whereas z_i is a resistor. 

In the frequency domain the capacitor is represented as \[\frac{1}{SC}\]  
where S=j\omega and z_i is represented as a R.  

*pic* 

\[\frac{Vo(s)}{Vi(s)} \rightarrow -\frac{1}{SCR}\]


** How the inverting integrator produces triangle waves 

As the integrator circuit takes in the square input formthe comparator, it integrates
the square wave, thus outputting a triangle wave. 

This can be by putting this circuit in time domain. 

*pic* 

The function of the capacitor in time domain is as follows: 

\[C = \frac{Q}{V}\]   

\[Q = CV \rightarrow  Q = \int_{}{}i(t)dt\]

\[CV = \int_{}{}i(t)dt\]


\[v_c(t) = \frac{1}{c}\int_{}{} i(t)dt\]


\[0-v_c(t) + V_c(t) = v_o(t) \rightarrow -\frac{1}{C}\int_{}{}i(t)dt + V_c(t) \]

Where v_c is the varying voltage by time and V_c is the initial voltage of the
capacitor. v_o and V_o are the output voltage of the circuit.


\[V_o(t) = -\frac{1}{RC}\int_{}{}v_i(t)dt + V_c(t)\]


As can be seen from above, the inverting component is the negative sign right infront
of \[\frac{1}{RC}\].  

As can be seen the compoenet of the output voltage is the integral of the input.  

*PIC* 

Now that we have figured the triangle wave generator, it is time to figure the square
wave generator.  

The square wave generator will act as both one of the input for the triangle wave
generator and one of the output waveforms that the user can select. 

This will done through the _Bistable Multivibrator_ or _Comparator with Hysteresis_. 

